### ISSUE TITLE
Implement Entitylimit

### ISSUE THREAD

**Issue by Blatower21** [BentoBoxWorld/addon-limits#15]
Just a reminder (suggested in Discord) about implementing entitylimit as it is said in the addon's notes. Is a very important feature that allow us a better server's perfomance and moderated game expierience mainly with chicken, endermans and pigman limits. Really waiting for it!

**Comment by tastybento** [comment]
Yes, I understand. I'm working on another project right now that I have to do, but it's on the to-do list.

**Comment by Icalave** [comment]
I know you have alot to work on Tasty just curious where on the list is entity limiting per island. Just so I can get a rough estimate in my head :).Using a per chunk limitation method atm

**Comment by tastybento** [comment]
let me look at this again and scope the effort.

**Comment by tastybento** [comment]
Have a try of the latest release 0.2.0 and let me know how it works for you.

**Comment by Icalave** [comment]
As far as I can see so far the limiting of entities appears to be working fine :smiley: 

Only 2 not issues but curiosities on if these would be hard to tie into the plugin

-Entity grouping rather than individual mob limits (not to fuss'd about this but think some people would prefer)

-Then second one is it possible to limit per world as for example our nether dimension is the vanilla version so there isn't per island area there
              - Like as an example could I set up a region that would be consider'd an "island" for that whole world and the plugin would limit the mobs there by whatever I defined each island to be


And thirdly where can I donate to you guys since you updated this with entities within a day for me :smiley:

**Comment by tastybento** [comment]
I'll look into the adding world feature - could you make another request for it?

For the entity grouping, it might be possible. 

You can donate to donate@bentobox.world - right now we prefer US$ Amazon gift cards but PayPal can work too. Thanks for your support!
