### ISSUE TITLE
Permission for limits

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/addon-limits#5]
It would be nice if we could give permissions to players to increase the limit of a specific entity, like how you can give permissions to increase island protection radius.

For example; the permission for hopper could be bskyblock.island.limit.HOPPER.<number/limit>

**Comment by TheWranger** [comment]
By adding this, it would allow for servers to finally control limits on islands.

**Comment by tastybento** [comment]
This could be done, but there are some limitations around teams. The issue is that permissions are per-player, so if you were to use permissions, then every player on the team would need them. Also, you'd need to remove those perms if they left, or gave them back, etc.
I think it would be better to try and do per-island control limits rather than use permissions. That way, you only need to define it once and it'll stick to the the island.

**Comment by TheWranger** [comment]
Could you not just make it so that only the owner's permissions are taken into account (like what's done with island protection range)?

**Comment by tastybento** [comment]
Yes, it could be possible. I'll look into it.

**Comment by tastybento** [comment]
Okay added. You should do a clean install because the config.yml has changed.
